version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rackup --host 0.0.0.0 --port $PORT
    volumes:
      - .:/usr/src/app
    ports:
      - "9292:${PORT}"
    depends_on:
      - db
    env_file: .env
